### ISSUE TITLE
October CMS broken after installing Ratchet 

### ISSUE THREAD

**Issue by daslicht** [leocavalcante/oc-websockets#2]
Hi,
when I install Ratchet in the root of my project using composer i get the following error:

![](http://i.imgur.com/Cj0wabq.png)

idea?

**Comment by leocavalcante** [comment]
Hi,
after Ratchet install, did composer update anything else?
It seams a problem with RainLab Pages plugin, not with WebSockets.

Can it be reproduced in a fresh new October clone, without any other plugins for example?

**Comment by daslicht** [comment]
not yet, composer do not throw any errors when installing other plugins.

**Comment by daslicht** [comment]
composer do not throw any errors

**Comment by leocavalcante** [comment]
Try to update de RainLab.Pages plugin. By the print screen, the error seams to be on that.

You can take a look for all the source code, neither OcWebsockets nor Ratchet tries to redeclare `Cms\Classes\Content::$fillable`

Also take a look at rainlab/pages-plugin#147 and rainlab/pages-plugin#148

I just did a clean install of a October project and added the plugin. Everything worked fine.

**Comment by daslicht** [comment]
I just created a clean october installation and created a plugin called 'Chat' and installed ratchet like this to it:
```
composer require cboden/ratchet
```
Where do I need to run ```php artisan websockets:run``` now ?
